// GENERATED CODE. DON'T MODIFY. Look at SpritesExporter.cs.
export let animationsJsons: { [name: string]: any } = {};
export let animationGifs: { [name: string]: any } = {};
animationsJsons['WalkAnimations.Normal'] = require('./WalkAnimations/Normal.json');
animationGifs['WalkAnimations.Normal'] = require('./WalkAnimations/Normal.gif');
animationsJsons['WalkAnimations.Jump'] = require('./WalkAnimations/Jump.json');
animationGifs['WalkAnimations.Jump'] = require('./WalkAnimations/Jump.gif');
animationsJsons['WalkAnimations.Run'] = require('./WalkAnimations/Run.json');
animationGifs['WalkAnimations.Run'] = require('./WalkAnimations/Run.gif');
animationsJsons['WalkAnimations.OneLeg'] = require('./WalkAnimations/OneLeg.json');
animationGifs['WalkAnimations.OneLeg'] = require('./WalkAnimations/OneLeg.gif');
animationsJsons['WaitAnimations.Iddle'] = require('./WaitAnimations/Iddle.json');
animationGifs['WaitAnimations.Iddle'] = require('./WaitAnimations/Iddle.gif');
animationsJsons['WaitAnimations.Jump'] = require('./WaitAnimations/Jump.json');
animationGifs['WaitAnimations.Jump'] = require('./WaitAnimations/Jump.gif');
animationsJsons['WaitAnimations.Dance'] = require('./WaitAnimations/Dance.json');
animationGifs['WaitAnimations.Dance'] = require('./WaitAnimations/Dance.gif');
animationsJsons['WaitAnimations.Rotate'] = require('./WaitAnimations/Rotate.json');
animationGifs['WaitAnimations.Rotate'] = require('./WaitAnimations/Rotate.gif');
